services:
  - type: web
    name: habit-recoder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: habit-recoder-db
          property: connectionString

databases:
  - name: habit-recoder-db
    databaseName: habit_recoder
    user: habit_recoder